16 ability to register package routes in required place of the app
RonasIT/laravel-chat pull request #19
Opened 2024-11-13 12:18 UTC by RGO230

2024-11-13 12:20 UTC, RGO230 commented
commit has merge branches, because they need for testing this functional

2024-11-14 02:01 UTC, DenTray requested changes

2024-11-14 02:01 UTC, DenTray commented on src/ChatServiceProvider.php
> +        Route::macro('when', fn ($condition, $callback) => ($condition) ? $callback() : null);
let's move `when` route macros to the laravel helpers package

2024-11-18 07:03 UTC, DenTray requested changes

2024-11-18 07:03 UTC, DenTray commented on composer.json
> +        "laravel/framework": "^11.21",
let's use 30 minor version 

```suggestion
        "laravel/framework": "^11.30",
```

2024-11-18 07:03 UTC, DenTray commented on config/chat.php
> +        'media_model' => RonasIT\Media\Models\Media::class,
let's remove it from this branch

2024-11-19 07:51 UTC, DenTray requested changes

2024-11-19 07:51 UTC, DenTray commented on config/chat.php
> -use App\Models\Media;
please revert these changes

2024-11-19 07:51 UTC, DenTray commented on src/ChatServiceProvider.php
> +
```suggestion
```

2024-11-19 09:00 UTC, DenTray requested changes

2024-11-19 09:00 UTC, DenTray commented on src/ChatRouter.php
> +                when($options['conversations_get_by_user_id'], fn () => $this->post('users/{userId}/conversation', 'getByUserId')->name('conversations.create.get.user.by.id'));
```suggestion
                when($options['conversations_get_by_user_id'], fn () => $this->post('users/{userId}/conversation', 'getByUserId')->name('conversations.get_by_user_id'));
```

2024-11-19 09:00 UTC, DenTray commented on config/chat.php
> +use App\Models\Media;
```suggestion
RonasIT\Media\Models\Media;
```

2024-11-19 09:01 UTC, DenTray approved these changes

2024-11-19 09:01 UTC, DenTray commented on config/chat.php
> +RonasIT\Media\Models\Media;
```suggestion
use RonasIT\Media\Models\Media;
```

2024-11-19 09:01 UTC, DenTray approved these changes

2024-11-19 09:02 UTC, merged